### ISSUE TITLE
Event classifier error log

### ISSUE THREAD

**Issue by wangxiaojia-wxj** [toncenter/ton-indexer#103]
ERROR:__main__:Marking trace as failed tSoIpSNT9PQHB9g0+SJx/HDPyTWy7OPfVyHATK7H8TQ= - '<' not supported between instances of 'int' and 'NoneType'
ERROR:__main__:Marking trace as failed /gGtXb5B77OLZRtanL7ySRQ4E9jQxexLDmOEcYXRbio= - '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/app/event_classifier.py", line 220, in <module>
    asyncio.run(start_processing_events_from_db(args))
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/event_classifier.py", line 76, in start_processing_events_from_db
    pool.map(process_event_batch, split_into_batches(ids, args.batch_size))
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f7f1dab4860>'. Reason: 'PicklingError("Can't pickle <class 'sqlalchemy_utils.types.pg_composite.ton_transfer_details'>: attribute lookup ton_transfer_details on sqlalchemy_utils.types.pg_composite failed")'

Event classifier error log

**Comment by wangxiaojia-wxj** [comment]
The database has this type of ton_transfer_details, and the classifier is stuck and no longer working, How to solve it?

**Comment by kdimentionaltree** [comment]
Hello, event classifier was significantly improved in v1.2. This issue was fixed as well.
