### ISSUE TITLE
Index API panic in v1.1.0

### ISSUE THREAD

**Issue by aghamir** [toncenter/ton-indexer#84]
Hi,
After upgrading to new version, index-api get panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa6a07f]

goroutine 8 [running]:
github.com/jackc/pgx/v5/pgtype.(*Map).RegisterType(0xc0001cd570, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.6.0/pgtype/pgtype.go:253 +0x1f
github.com/kdimentionaltree/ton-index-go/index.afterConnectRegisterTypes({0x193b6d0, 0xc0000a4f00}, 0xc0001ed680)
	/go/app/index/database.go:26 +0xec
github.com/jackc/pgx/v5/pgxpool.NewWithConfig.func1({0x193b6d0, 0xc0000a4f00})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.6.0/pgxpool/pool.go:233 +0x1a8
github.com/jackc/puddle/v2.(*Pool[...]).initResourceValue.func1()
	/go/pkg/mod/github.com/jackc/puddle/v2@v2.2.1/pool.go:409 +0xdc
created by github.com/jackc/puddle/v2.(*Pool[...]).initResourceValue in goroutine 1
	/go/pkg/mod/github.com/jackc/puddle/v2@v2.2.1/pool.go:407 +0xf6
```

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@aghamir 
Support.
  {c}2024

**Comment by BaoHG1508** [comment]
Have you solved this yet? @aghamir
